require "stringio"

module Profiles
  # Dev/staging-only demo seeder for Date9ja, so there is a real pool of
  # active, visible, opposite-gender members to browse/discover/like while
  # testing — the same real gates a genuine member goes through
  # (Profiles::Publication.activate! only flips a profile live once
  # Profiles::Completion says it is genuinely complete against Date9ja's own
  # REQUIRED_* contract, and photos go through the real
  # Media::ProcessProfilePhotoJob pipeline). No discovery/matching special
  # casing, no serializer spoofing, no validation bypass.
  #
  # Reuses the same on-disk image catalogue (docs/user-images/{ladies,guys})
  # and identity/photo persistence as Profiles::DatezaDemoSeed
  # (Profiles::DemoSeed::Catalog / ::Builder) — only the *content* differs,
  # because Date9ja's completion contract is its own (is_nigerian, state of
  # origin, tribe, and the 10 required relationship-value option groups) and
  # none of DateZA/HookUs's option groups (intents, vibes, pets, …) are
  # enabled for Date9ja.
  module Date9jaDemoSeed
    DEFAULT_ROOT = DemoSeed::DEFAULT_ROOT
    BRAND_SLUG = "date9ja".freeze
    SEED_TAG = "date9ja_demo".freeze
    SEED_DEVICE = "date9ja-seed-demo".freeze
      SYNTHETIC_LAST_NAME = "Demo".freeze
      # Keep one deterministic card visibly representative of the profile-video
      # contract. The bytes are generated by the same synthetic corpus renderer
      # used by the Date9ja media rehearsal, then passed through the real upload
      # and processing pipeline below.
      VIDEO_INTRO_INDEX = 0

    Summary = DemoSeed::Summary

    def self.guard!(...)
      DemoSeed.guard!(...)
    end

    def self.call(root: DEFAULT_ROOT, dry_run: false, io: $stdout)
      Runner.new(root:, dry_run:, io:).call
    end

    class Runner
      # Real Date9ja option codes (scripts/date9ja source_census-attested —
      # see Date9jaProfileCatalog / SensitiveVocabularies), one plausible mix
      # per group. Any subset a person draws from here is guaranteed valid.
      RELATIONSHIP_INTENTS = %w[ long_term_relationship marriage courtship dating friendship ].freeze
      HAS_CHILDREN = %w[ yes no ].freeze
      WANTS_CHILDREN = %w[ yes maybe no open ].freeze
      RELIGIONS = %w[ christian muslim spiritual agnostic ].freeze
      FAMILY_INVOLVEMENT = %w[ must_approve blessing_matters later_when_serious my_decision_alone ].freeze
      FAITH_PRACTICE = %w[ central_daily practice_regularly practice_flexibly not_a_factor ].freeze
      MONEY_PROVIDING = %w[ both_one_purse joint_and_personal split_bills earner_carries_more ].freeze
      SETTLEMENT = %w[ nigeria_staying_returning diaspora_visiting_often open_to_relocate ].freeze
      CHILDREN = %w[ want_soon want_no_rush open_either_way dont_want ].freeze
      CONFLICT = %w[ talk_now cool_off_first trusted_mediator ].freeze
      TRIBES = %w[ igbo yoruba hausa edo ijaw ].freeze

      # name => [state, latitude, longitude] — real Nigerian cities so seeded
      # profiles read as genuinely Nigerian, matching Date9ja's brand.
      CITIES = {
        "Lagos" => [ "Lagos", 6.5244, 3.3792 ],
        "Abuja" => [ "FCT", 9.0765, 7.3986 ],
        "Ibadan" => [ "Oyo", 7.3775, 3.9470 ],
        "Port Harcourt" => [ "Rivers", 4.8156, 7.0498 ],
        "Enugu" => [ "Enugu", 6.5244, 7.5086 ],
        "Kano" => [ "Kano", 12.0022, 8.5920 ]
      }.freeze

      BIOS = [
        "Nigerian at heart, wherever life has taken me. Looking for someone " \
          "who values faith, family, and good jollof opinions.",
        "Building a life, a career, and hopefully something real with the " \
          "right person. Let's talk about what actually matters.",
        "Not here for games — here for something serious, with room to " \
          "laugh along the way.",
        "Grounded in my roots, open to where love takes me next."
      ].freeze

      def initialize(root:, dry_run:, io:)
        @root = root
        @dry_run = dry_run
        @io = io
      end

      def call
        Date9jaDemoSeed.guard!
        brand = resolve_brand!
        people = DemoSeed::Catalog.call(root: @root)
        created = updated = photos = video_intros = skipped = 0
        ladies = people.count { |person| person.gender == "woman" }

        people.each_with_index do |person, index|
          content = content_for(person, index:)
          outcome = @dry_run ? plan(person:, brand:) : build(person:, content:, brand:)
          outcome.created ? created += 1 : updated += 1
          photos += outcome.photos_attached
          video_intros += seed_video_intro(person:, brand:, index:) if index == VIDEO_INTRO_INDEX
        rescue StandardError => e
          skipped += 1
          @io.puts "  ! skipped #{person.slug}: #{e.class}: #{e.message}"
        end

        Summary.new(
          created:, updated:, ladies:, guys: people.size - ladies,
          photos_attached: photos, skipped:, dry_run: @dry_run
        ).tap do |summary|
          @video_intros = video_intros
          report(summary)
        end
      end

      private

      def email_for(person)
        "seed+d9-#{person.slug}@date9ja.test"
      end

      def identity_attributes(person)
        { first_name: person.display_name, last_name: SYNTHETIC_LAST_NAME }
      end

      # Builds a Profiles::DemoSeed::Content::Result — the same shape
      # DemoSeed::Builder consumes for any brand — populated with values that
      # satisfy Date9ja's own REQUIRED_* contract (Date9jaProfileCatalog)
      # rather than DateZA/HookUs's option groups.
      def content_for(person, index:)
        city, (state, lat, lng) = CITIES.to_a[index % CITIES.size]
        offset = 10 + ((person.slug.hash.abs % 320))
        birthdate = person.age.years.ago.to_date - offset

        DemoSeed::Content::Result.new(
          birthdate:,
          profile: {
            display_name: person.display_name,
            bio: BIOS[index % BIOS.size],
            gender: person.gender,
            country_code: "NG",
            city:,
            is_nigerian: true,
            state_of_origin: state,
            willing_to_relocate: [ true, false ].sample(random: Random.new(index))
          },
          preference: {
            interested_in: [ person.gender == "woman" ? "man" : "woman" ],
            min_age: 21,
            max_age: 55
          },
          options: {
            "relationship_intent" => [ pick(RELATIONSHIP_INTENTS, index, 0) ],
            "has_children" => [ pick(HAS_CHILDREN, index, 1) ],
            "wants_children" => [ pick(WANTS_CHILDREN, index, 2) ],
            "religion" => [ pick(RELIGIONS, index, 3) ],
            "family_involvement" => [ pick(FAMILY_INVOLVEMENT, index, 4) ],
            "faith_practice" => [ pick(FAITH_PRACTICE, index, 5) ],
            "money_providing" => [ pick(MONEY_PROVIDING, index, 6) ],
            "settlement" => [ pick(SETTLEMENT, index, 7) ],
            "children" => [ pick(CHILDREN, index, 8) ],
            "conflict" => [ pick(CONFLICT, index, 9) ],
            "tribe" => [ pick(TRIBES, index, 10) ]
          },
          prompts: [],
          location: { latitude: lat + jitter(index, 11), longitude: lng + jitter(index, 12) },
          activity: %i[ online active_today this_week inactive ][index % 4],
          verified: index.even?,
          new_here: index < 3
        )
      end

      def pick(pool, index, salt)
        pool[(index + salt) % pool.size]
      end

      def jitter(index, salt)
        (((index + salt) * 37) % 61 - 30) / 1000.0
      end

      def build(person:, content:, brand:)
        DemoSeed::Builder.call(
          person:, content:, brand:, email: email_for(person), seed_tag: SEED_TAG,
          identity_attributes: identity_attributes(person), seed_device: SEED_DEVICE,
          # Demo people are fabricated showcase data, never real members (see
          # DemoSeed.guard!, non-production only) — they exist to populate a
          # working Introductions/Explore pool immediately.
          photo_initial_state: Media::PhotoPolicy::IMMEDIATE
        )
      end

      # Seed one real, safe video intro so Explore/Introductions/Likes cards can
      # exercise the same deliverability contract as a member upload. This is
      # deliberately Date9ja-specific: the shared DemoSeed builder remains
      # photo-only for other brands.
      def seed_video_intro(person:, brand:, index:)
        identifier = IdentityIdentifier.kept.find_by(kind: :email, normalized_value: email_for(person))
        profile = Profile.kept.find_by(user: identifier&.user, brand:) if identifier
        return 0 if profile && ProfileVideo.kept.exists?(profile:)
        return 1 if @dry_run
        return 0 unless profile

        content_type = "video/mp4"
        bytes = Date9ja::Snapshot::SyntheticVideoMedia.render(
          source_blob_id: "date9ja-demo-video-#{person.slug}-#{index}",
          canonical_content_type: content_type
        )
        key = Media::ObjectKey.profile_video_original(
          brand:, user: profile.user, profile:, content_type:
        )
        blob = ActiveStorage::Blob.create_and_upload!(
          io: StringIO.new(bytes), key:, filename: "#{person.slug}-intro.mp4",
          content_type:, service_name: Media::StorageResolver.service_name(brand:)
        )
        initial = Media::VideoPolicy.initial_state(brand:)
        video = Profiles::VideoUpload.build_video!(
          profile:, user: profile.user, brand:, blob:,
          status: initial.status, visibility: initial.visibility
        )
        Media::ProcessProfileVideoJob.perform_now(video.id)
        1
      end

      def plan(person:, brand:)
        identifier = IdentityIdentifier.kept.find_by(kind: :email, normalized_value: email_for(person))
        profile = Profile.kept.find_by(user: identifier&.user, brand:) if identifier
        seeded = profile ? profile.profile_photos.kept.filter_map { |p| p.metadata["seed_basename"] }.to_set : Set.new
        to_attach = person.image_paths.count { |path| !seeded.include?(File.basename(path)) }
        DemoSeed::Builder::Outcome.new(created: identifier.nil?, photos_attached: to_attach)
      end

      def resolve_brand!
        brand = Brand.kept.find_by(slug: BRAND_SLUG)

        if brand.nil?
          raise DemoSeed::Catalog::Error, "Date9ja brand (slug=#{BRAND_SLUG}) not found" if @dry_run

          brand = Brands::Date9jaInstaller.call
        end

        Date9jaProfileCatalog.install!(brand:) unless @dry_run || catalog_ready?(brand)
        brand
      end

      def catalog_ready?(brand)
        required = Date9jaProfileCatalog::REQUIRED_OPTION_GROUPS + %w[ tribe ]
        present = brand.profile_option_groups.kept.where(key: required).pluck(:key)
        (required - present).empty?
      end

      def report(summary)
        @io.puts ""
        @io.puts "Date9ja demo seed #{summary.dry_run ? 'DRY RUN (no changes written)' : 'complete'}"
        @io.puts ""
        @io.puts "Profiles #{summary.dry_run ? 'to create' : 'created'}: #{summary.created}"
        @io.puts "Profiles #{summary.dry_run ? 'to update' : 'updated'}:  #{summary.updated}"
        @io.puts "Ladies: #{summary.ladies}"
        @io.puts "Guys:   #{summary.guys}"
        @io.puts "Photos #{summary.dry_run ? 'to attach' : 'attached'}: #{summary.photos_attached}"
        @io.puts "Video intros #{summary.dry_run ? 'to attach' : 'attached'}: #{@video_intros || 0}"
        @io.puts "Skipped: #{summary.skipped}"
      end
    end
  end
end
